"""Decision notes are written in my own voice, and they stay that way.

This repository is public and doubles as my portfolio. For months the comments, design
locks and specs recorded my decisions as "(user, 2026-07-12)", "user directive: …" and
"locked with the user": accurate, but written from the outside, as if someone else were
narrating my project. I rewrote ~200 of them into the first person ("my call,
2026-07-12"). This pins that so the old phrasing cannot drift back in one note at a time.

"The user" still appears legitimately wherever it means an app user (a student's Eyecon,
a chat message, a per-user rate limit), so the patterns below match only the
decision-record phrasings, and the samples prove both sides.

Out of scope: CLAUDE.md, .claude/ and workflows/ are briefs written TO an assistant, where
"the user" correctly means me; .session-handoff.md is generated by /handoff.
"""
import re
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SKIP = ("CLAUDE.md", ".claude/", "workflows/", ".session-handoff.md", "frontend/package-lock.json",
        "tests/test_writing_voice.py")
EXT = (".py", ".ts", ".tsx", ".mjs", ".js", ".css", ".sh", ".md", ".yml")

OUTSIDE_VOICE = re.compile(
    r"\(user[,:]\s*\d{4}-\d\d-\d\d"            # (user, 2026-07-12)
    r"|\buser directive\b"
    r"|\buser'?s call\b"
    r"|\buser (?:rule|policy|decision)\b"
    r"|\(per (?:the )?user\)"
    r"|\bper the user's\b"
    r"|\blocked with the user\b"
    r"|\bthe user's explicit (?:go-ahead|greenlight|ask)\b"
    r"|\bconfirm(?:ed)? with the user\b",
    re.IGNORECASE,
)

OWNER_NARRATION = [
    "Declutter (user, 2026-07-12): a single-select card locks",
    "- **Toybox vibrancy** (2026-07-11, user directive: \"colors more bold\")",
    "## Decisions (locked with the user)",
    "Do NOT run this without the user's explicit go-ahead.",
    "Model tiering (user rule: default flash)",
    "- **Kept (per user):** the coach line",
    "the **150°–300° closure** (user's call, 2026-08-06)",
]
APP_USER = [
    "The tour is narrated by the user's live `<Eyecon>`",
    "The thread renders no bubbles until the user sends",
    "rate-limit keys differ per user / per forwarded IP",
    "the per-user student block rides in the user turn",
    "a missing anchor never traps the user",
    "Declutter (my call, 2026-07-12): a single-select card locks",
]


def test_the_pattern_tells_owner_narration_from_app_users():
    assert all(OUTSIDE_VOICE.search(s) for s in OWNER_NARRATION)
    assert not any(OUTSIDE_VOICE.search(s) for s in APP_USER)


def test_no_decision_note_narrates_me_in_the_third_person():
    files = subprocess.run(["git", "ls-files"], cwd=ROOT, capture_output=True, text=True,
                           check=True).stdout.splitlines()
    checked, hits = 0, []
    for f in files:
        if not f.endswith(EXT) or f.startswith(SKIP):
            continue
        checked += 1
        text = (ROOT / f).read_text(encoding="utf-8", errors="replace")
        for n, line in enumerate(text.splitlines(), 1):
            if OUTSIDE_VOICE.search(line):
                hits.append(f"{f}:{n}: {line.strip()[:120]}")
    assert checked > 500, f"only {checked} files scanned; the file listing broke"
    assert not hits, "write these in the first person (e.g. 'my call, DATE'):\n" + "\n".join(hits)
