"""Task 2 of the Selena 3D-portrait plan: generate + store (paid path, wired MOCK-safe).

These tests NEVER fire a live image generation. They verify the wiring only:
- render_portrait REFUSES to run in MOCK_MODE (so tests/CI can never fake art),
- when live, it builds the config→prompt and returns the generated bytes (flash-image),
- store_portrait uploads `<hash>.png` to the public selena-avatars bucket and returns
  the public URL.
The live Gemini call and the Supabase upload are monkeypatched out.
"""
import pytest

from tools.avatar import portrait
from tools.kb import supabase_client


def test_render_portrait_refuses_in_mock_mode(monkeypatch):
    # The default test env is MOCK_MODE; assert we never fabricate art there.
    monkeypatch.setattr(portrait, "MOCK_MODE", True)
    with pytest.raises(RuntimeError, match="MOCK_MODE"):
        portrait.render_portrait({"bodyColor": "aqua"})


def test_render_portrait_builds_prompt_and_returns_bytes(monkeypatch):
    captured = {}

    def fake_gen(prompt, model=None, **kw):
        captured["prompt"] = prompt
        captured["model"] = model
        return b"PNGDATA"

    monkeypatch.setattr(portrait, "MOCK_MODE", False)
    monkeypatch.setattr(portrait.generate_sprites, "generate_image_bytes", fake_gen)

    out = portrait.render_portrait({"topper": "crown", "glasses": "none"})

    assert out == b"PNGDATA"
    p = captured["prompt"].lower()
    assert "one" in p and "eye" in p              # the invariant Iris contract is carried
    assert "crown" in p                           # a set option is reflected
    assert "glasses" not in p                     # a `none` option contributes nothing
    assert captured["model"] == "gemini-3.1-flash-image"  # flash-image (pro 504s under load)


def test_render_portrait_raises_when_no_image(monkeypatch):
    monkeypatch.setattr(portrait, "MOCK_MODE", False)
    monkeypatch.setattr(portrait.generate_sprites, "generate_image_bytes", lambda *a, **k: None)
    with pytest.raises(RuntimeError):
        portrait.render_portrait({"bodyColor": "aqua"})


def test_store_portrait_defaults_to_png(monkeypatch):
    seen = {}

    def fake_upload(path, data, content_type="image/png"):
        seen["path"] = path
        seen["data"] = data
        seen["ctype"] = content_type
        return f"https://cdn.example/selena-avatars/{path}"

    monkeypatch.setattr(supabase_client, "upload_avatar", fake_upload)

    url = portrait.store_portrait("abc123def456ab00", b"PNGDATA")

    assert seen["path"] == "abc123def456ab00.png"   # stored by config hash
    assert seen["data"] == b"PNGDATA"
    assert seen["ctype"] == "image/png"
    assert url.endswith("abc123def456ab00.png")


def test_store_portrait_uses_jpg_for_jpeg_bytes(monkeypatch):
    # flash-image actually returns JPEG — store it with the right extension + content-type.
    seen = {}

    def fake_upload(path, data, content_type="image/png"):
        seen["path"] = path
        seen["ctype"] = content_type
        return f"https://cdn.example/selena-avatars/{path}"

    monkeypatch.setattr(supabase_client, "upload_avatar", fake_upload)

    jpeg = b"\xff\xd8\xff\xe0\x00\x10JFIF" + b"\x00" * 32
    url = portrait.store_portrait("deadbeefdeadbeef", jpeg)

    assert seen["path"] == "deadbeefdeadbeef.jpg"
    assert seen["ctype"] == "image/jpeg"
    assert url.endswith(".jpg")


def test_upload_avatar_targets_public_selena_avatars_bucket(monkeypatch):
    calls = {}

    class FakeBucket:
        def upload(self, path, file, file_options):
            calls["upload"] = (path, file, file_options)

        def get_public_url(self, path):
            return f"https://cdn/{path}"

    class FakeStorage:
        def from_(self, bucket):
            calls.setdefault("bucket", bucket)
            return FakeBucket()

    class FakeClient:
        storage = FakeStorage()

    monkeypatch.setattr(supabase_client, "get_client", lambda: FakeClient())

    url = supabase_client.upload_avatar("h.jpg", b"X", content_type="image/jpeg")

    assert calls["bucket"] == "selena-avatars"
    assert calls["upload"][0] == "h.jpg"
    assert calls["upload"][2]["content-type"] == "image/jpeg"
    assert url == "https://cdn/h.jpg"
