"""Static daily check-in MCQ pool — easy "brain icebreaker" questions per role.

Every entry is a multiple-choice question grounded in the SNEC knowledge base
(Module 1 markdown, the skill checklists, and the OSCE scripts), tagged with its
`source`. Difficulty is deliberately the easiest of all features (single-fact
recall). Language is short and neutral.

Shape:
    {"topic", "question", "options": [4 strings], "answer": int,
     "explanation", "source"}

Convention: the CORRECT option is authored FIRST (answer index 0). The API
(GET /api/checkin/question) shuffles option order per serve so the answer is not
always in the same position, and grading is deterministic (selected option text
== correct option text) — no AI marks the check-in.

Role mapping (each question only touches its role's field of study):
- OT  -> ophthalmic investigations / imaging field (OT_POOL).
- OA and PSA study almost the same course, so they SHARE the clinical base
  pool (CLINICAL_POOL): emergencies, triage, history, basic eye evaluation,
  OPD skills, abbreviations.

Served one-per-day, rotated so a student cycles the whole pool before repeats
(tools.shared.static_pools.pick_by_day_count).
"""

# ── Clinical base pool — OA + PSA (they study almost the same thing) ──────────
CLINICAL_POOL: list[dict] = [
    {"topic": "ocular emergencies", "question": "Which of these is classed as an ocular emergency?",
     "options": ["Acute glaucoma", "Mild long-term floaters", "A stable squint", "Needing new glasses"], "answer": 0,
     "explanation": "Acute glaucoma is one of the listed ocular emergencies.", "source": "Module 1 — Ocular Emergencies"},
    {"topic": "chemical injury", "question": "The first step for a chemical splash to the eye is to:",
     "options": ["Start irrigation immediately", "Patch the eye", "Book a routine clinic", "Give painkillers and wait"], "answer": 0,
     "explanation": "Chemical injury is Triage Category 1 — irrigate immediately.", "source": "Module 1 — Triage (Cat 1)"},
    {"topic": "triage", "question": "A Triage Category 1 case should be seen within:",
     "options": ["10 minutes", "30 minutes", "2 hours", "1 day"], "answer": 0,
     "explanation": "Category 1 (e.g. chemical burns, CRAO) is within 10 minutes.", "source": "Module 1 — Triage Categories"},
    {"topic": "triage", "question": "Which condition is Triage Category 4 (within 2 hours)?",
     "options": ["Conjunctivitis", "Chemical burn", "Penetrating eye injury", "Central retinal artery occlusion"], "answer": 0,
     "explanation": "Conjunctivitis is a Category 4 minor/chronic condition.", "source": "Module 1 — Triage (Cat 4)"},
    {"topic": "ocular emergencies", "question": "Sudden painless loss of vision should be treated as:",
     "options": ["An emergency", "A routine review", "Normal ageing", "A minor issue"], "answer": 0,
     "explanation": "Sudden painless visual loss (e.g. CRAO/CRVO) is an emergency.", "source": "Module 1 — Triage (Cat 1/2)"},
    {"topic": "acute glaucoma", "question": "Acute angle-closure glaucoma typically shows a pupil that is:",
     "options": ["Fixed and mid-dilated (large oval)", "Small and reactive", "Normal", "Constantly moving"], "answer": 0,
     "explanation": "Acute glaucoma gives a fixed, mid-dilated oval pupil.", "source": "Module 1 — Ocular Emergencies"},
    {"topic": "red eye", "question": "A red eye with marked discharge but no pain or photophobia is most likely:",
     "options": ["Conjunctivitis", "Acute glaucoma", "Iritis", "Keratitis"], "answer": 0,
     "explanation": "Marked discharge with no pain/photophobia points to conjunctivitis.", "source": "Module 1 — Red Eye DDx"},
    {"topic": "red eye", "question": "In the red-eye comparison, marked photophobia is most typical of:",
     "options": ["Iritis", "Conjunctivitis", "A normal eye", "A stye"], "answer": 0,
     "explanation": "Iritis classically has marked photophobia.", "source": "Module 1 — Red Eye DDx"},
    {"topic": "trauma", "question": "For a suspected penetrating eye injury you should:",
     "options": ["Apply a shield and not press on the eye", "Irrigate forcefully", "Pad firmly", "Massage the eye"], "answer": 0,
     "explanation": "Protect with a shield; do not put pressure on a penetrating injury.", "source": "Module 1 — Triage (Cat 1)"},
    {"topic": "retinal detachment", "question": "New floaters and flashes, especially with a retinal history, should raise suspicion of:",
     "options": ["Retinal detachment", "Conjunctivitis", "Dry eye", "Blepharitis"], "answer": 0,
     "explanation": "Sudden floaters/flashes suggest possible retinal detachment.", "source": "Module 1 — Triage (Cat 3)"},
    {"topic": "history taking", "question": "Severe eye pain with nausea and vomiting should make you consider:",
     "options": ["Acute angle-closure glaucoma", "Dry eye", "A stye", "Allergy"], "answer": 0,
     "explanation": "Severe pain + nausea/vomiting suggests acute angle-closure glaucoma.", "source": "Module 1 — Pain Assessment"},
    {"topic": "history taking", "question": "Pain should be documented using a scale of:",
     "options": ["0 to 10", "0 to 3", "1 to 100", "A to E"], "answer": 0,
     "explanation": "Use a 0–10 pain scale.", "source": "Module 1 — Pain Assessment"},
    {"topic": "history taking", "question": "Which family history is important to ask about in eye care?",
     "options": ["Glaucoma", "Broken bones", "Hearing loss", "Tonsillitis"], "answer": 0,
     "explanation": "Family history of glaucoma (and squint, etc.) is relevant.", "source": "Module 1 — Family History"},
    {"topic": "history taking", "question": "Which medication is important to ask about because of bleeding risk?",
     "options": ["Anti-coagulants", "Paracetamol", "Vitamin C", "Antacids"], "answer": 0,
     "explanation": "Anti-coagulants matter for bleeding risk in eye care/surgery.", "source": "Module 1 — General Health History"},
    {"topic": "history taking", "question": "When a patient reports reduced vision, an important question is whether it was:",
     "options": ["Sudden or gradual", "Funny or sad", "Loud or quiet", "Hot or cold"], "answer": 0,
     "explanation": "Establish if the visual change was sudden or gradual, one or both eyes.", "source": "Module 1 — Ocular History"},
    {"topic": "visual acuity", "question": "Normal distance visual acuity on the Snellen chart is:",
     "options": ["6/6", "6/60", "3/6", "20/200"], "answer": 0,
     "explanation": "6/6 is normal distance acuity.", "source": "Module 1 — Visual Acuity"},
    {"topic": "visual acuity", "question": "In '6/12', the bottom number refers to the distance at which a:",
     "options": ["Normal eye could read that line", "Doctor stands", "Chart is stored", "Pupil dilates"], "answer": 0,
     "explanation": "VA = testing distance / distance a normal eye reads the line.", "source": "Module 1 — Visual Acuity"},
    {"topic": "visual acuity", "question": "By convention, which eye is tested first?",
     "options": ["The right eye", "The left eye", "Both together", "Either, randomly"], "answer": 0,
     "explanation": "Always start with the right eye by convention.", "source": "Module 1 — VA Procedure"},
    {"topic": "pinhole", "question": "A pinhole is applied when vision is:",
     "options": ["6/12 or above", "Always", "Only 6/6", "Never"], "answer": 0,
     "explanation": "Use a pinhole if vision is 6/12 or above.", "source": "Module 1 — VA Procedure"},
    {"topic": "pinhole", "question": "If vision improves with a pinhole, the cause is likely:",
     "options": ["A refractive error", "Glaucoma", "A blocked tear duct", "A brain tumour"], "answer": 0,
     "explanation": "Pinhole improvement indicates a refractive cause.", "source": "Module 1 — Pinhole Test"},
    {"topic": "visual acuity", "question": "If a patient cannot read 6/60 at all, the next step is to:",
     "options": ["Move to the 6/120 line", "Stop the test", "Dilate the pupil", "Switch off the lights"], "answer": 0,
     "explanation": "Proceed to 6/120 if 6/60 cannot be read.", "source": "Module 1 — VA Scenarios"},
    {"topic": "visual acuity", "question": "The correct order when vision is very poor is:",
     "options": ["Count Fingers, Hand Movement, Perception of Light, NPL", "NPL, PL, HM, CF", "HM, CF, NPL, PL", "PL, HM, NPL, CF"], "answer": 0,
     "explanation": "CF → HM → PL → NPL.", "source": "Module 1 — VA Scenarios"},
    {"topic": "visual acuity", "question": "The E chart is useful for patients who:",
     "options": ["Cannot read letters (children, non-readers)", "Wear glasses", "Have high IOP", "Are colour blind"], "answer": 0,
     "explanation": "The E chart suits young children, illiterate or non-English-speaking patients.", "source": "Module 1 — VA Charts"},
    {"topic": "near vision", "question": "The near vision chart is usually held at:",
     "options": ["About 35 cm", "6 metres", "1 metre", "10 cm"], "answer": 0,
     "explanation": "Near vision is tested at ~35 cm.", "source": "Module 1 — Near Vision"},
    {"topic": "near vision", "question": "Normal near vision is recorded as:",
     "options": ["N5", "N48", "6/6", "20/20"], "answer": 0,
     "explanation": "N5 is the finest normal near print.", "source": "Module 1 — Near Vision"},
    {"topic": "intraocular pressure", "question": "The normal range of intraocular pressure (IOP) is:",
     "options": ["10–21 mmHg", "21–35 mmHg", "0–7 mmHg", "35–50 mmHg"], "answer": 0,
     "explanation": "Normal IOP is about 10–21 mmHg.", "source": "Module 1 — IOP / NCT"},
    {"topic": "tonometry", "question": "Non-contact tonometry (NCT) measures pressure using:",
     "options": ["A puff of air", "A contact probe", "An eye drop", "A laser"], "answer": 0,
     "explanation": "NCT uses an air puff.", "source": "Module 1 — IOP / NCT"},
    {"topic": "tonometry", "question": "Before NCT you should ask the patient to:",
     "options": ["Remove glasses or contact lenses", "Close both eyes", "Look away", "Hold their breath"], "answer": 0,
     "explanation": "Glasses/contact lenses are removed before NCT.", "source": "Module 1 — NCT Procedure"},
    {"topic": "infection control", "question": "Between patients, the key infection-control step is to:",
     "options": ["Perform hand hygiene and wipe contact parts", "Change the chart", "Dim the lights", "Restart the computer"], "answer": 0,
     "explanation": "Hand hygiene and wiping machine contact parts prevent cross-infection.", "source": "Module 1 — Procedures"},
    {"topic": "auto-refraction", "question": "Auto-refraction provides an objective measure of:",
     "options": ["Refractive error", "Eye pressure", "Colour vision", "Tear volume"], "answer": 0,
     "explanation": "AR objectively measures refractive error.", "source": "Module 1 — Auto-Refraction"},
    {"topic": "keratometry", "question": "Auto-keratometry measures the:",
     "options": ["Corneal curvature", "Retinal thickness", "Visual field", "Pupil colour"], "answer": 0,
     "explanation": "AK measures corneal curvature (used for IOL calculation).", "source": "Module 1 — Auto-Keratometry"},
    {"topic": "colour vision", "question": "The Ishihara test screens for:",
     "options": ["Colour vision deficiency", "Glaucoma", "Cataract", "Squint"], "answer": 0,
     "explanation": "Ishihara plates screen for red-green colour deficiency.", "source": "Module 1 — Colour Vision"},
    {"topic": "macular function", "question": "The Amsler grid is used to detect:",
     "options": ["Central distortion (macular problems)", "High eye pressure", "Colour blindness", "Squint"], "answer": 0,
     "explanation": "The Amsler grid detects central field distortion/metamorphopsia.", "source": "Module 1 — Amsler Grid"},
    {"topic": "fall risk", "question": "Fall risk should be assessed in:",
     "options": ["All patients at each visit", "Only children", "Only inpatients", "No one"], "answer": 0,
     "explanation": "Assess every patient for fall risk at each visit.", "source": "Module 1 — Fall Risk"},
    {"topic": "fall risk", "question": "Which patient is at higher fall risk?",
     "options": ["A just-dilated, visually impaired elderly patient", "A young patient reading well", "A patient with new glasses", "A colour-blind patient"], "answer": 0,
     "explanation": "Post-dilation, elderly and visually impaired patients are higher risk.", "source": "Module 1 — Fall Risk"},
    {"topic": "eye drops", "question": "Before instilling any eye drop you must check the patient's:",
     "options": ["Allergy status", "Shoe size", "Postcode", "Favourite colour"], "answer": 0,
     "explanation": "Confirm the patient is not allergic before instilling.", "source": "Module 1 — Instillation of Eye Drops"},
    {"topic": "eye drops", "question": "An eye drop is instilled into the:",
     "options": ["Lower fornix (lower lid pocket)", "Centre of the cornea", "Upper lid skin", "Inner ear"], "answer": 0,
     "explanation": "Pull the lower lid down and drop into the lower fornix.", "source": "Module 1 — Instillation of Eye Drops"},
    {"topic": "eye drops", "question": "After instilling a drop you ask the patient to close the eye and:",
     "options": ["Apply gentle pressure near the nose", "Rub firmly", "Blink hard 10 times", "Look at a bright light"], "answer": 0,
     "explanation": "Gentle nasolacrimal pressure reduces systemic absorption.", "source": "Module 1 — Instillation of Eye Drops"},
    {"topic": "dilation", "question": "Common dilating drops include:",
     "options": ["Tropicamide and phenylephrine", "Timolol and latanoprost", "Saline and water", "Antibiotic ointment"], "answer": 0,
     "explanation": "Tropicamide 1% and phenylephrine 2.5% are common mydriatics.", "source": "Module 1 — Pupil Dilation"},
    {"topic": "dilation", "question": "After dilation, warn the patient about:",
     "options": ["Blurred near vision and light sensitivity", "Hearing changes", "Loss of taste", "Permanent blindness"], "answer": 0,
     "explanation": "Dilation blurs near vision and increases light sensitivity for 4–6 hours.", "source": "Module 1 — Pupil Dilation"},
    {"topic": "dilation safety", "question": "Dilation should be discussed with the nurse/doctor first if the patient has:",
     "options": ["Narrow angles", "Dry eyes", "Short sight", "Colour blindness"], "answer": 0,
     "explanation": "Narrow angles are a contraindication — check before dilating.", "source": "Module 1 — Pupil Dilation"},
    {"topic": "pre-operative", "question": "The dayward pre-op mnemonic 'DISM' stands for:",
     "options": ["Diagnosis, Indication, Surgery, Medical condition", "Drop, Inject, Scan, Measure", "Distance, IOP, Sight, Macula", "Dilate, Irrigate, Suture, Monitor"], "answer": 0,
     "explanation": "DISM = Diagnosis, Indication, Surgery planned, Medical conditions.", "source": "Module 1 — Dayward Pre-Op"},
    {"topic": "post-operative", "question": "During post-op eye dressing you observe the lids, wound and:",
     "options": ["Conjunctiva", "Eyebrows", "Hairline", "Earlobes"], "answer": 0,
     "explanation": "Observe lids, conjunctiva and the wound section during dressing.", "source": "Module 1 — Post-Op Dressing"},
    {"topic": "triaging", "question": "Triage is best described as:",
     "options": ["Assessing patients to determine clinical priority", "Booking surgery", "Cleaning equipment", "Filing records"], "answer": 0,
     "explanation": "Triage determines clinical priority.", "source": "Module 1 — Triaging"},
    {"topic": "abbreviations", "question": "'OD' refers to the:",
     "options": ["Right eye", "Left eye", "Both eyes", "Optic disc"], "answer": 0,
     "explanation": "OD = oculus dexter = right eye.", "source": "Module 1 — Abbreviations"},
    {"topic": "abbreviations", "question": "'OS' refers to the:",
     "options": ["Left eye", "Right eye", "Both eyes", "Outer sclera"], "answer": 0,
     "explanation": "OS = oculus sinister = left eye.", "source": "Module 1 — Abbreviations"},
    {"topic": "abbreviations", "question": "'TCU' in clinic notes means:",
     "options": ["To Come Up (follow-up)", "Total Cup Unit", "Treat Current Ulcer", "Two Colour Use"], "answer": 0,
     "explanation": "TCU = To Come Up, the next follow-up appointment.", "source": "Module 1 — Abbreviations"},
    {"topic": "abbreviations", "question": "'IOL' stands for:",
     "options": ["Intraocular Lens", "Inner Optic Layer", "Intraocular Light", "Iris Outer Line"], "answer": 0,
     "explanation": "IOL = intraocular lens, implanted in cataract surgery.", "source": "Module 1 — Abbreviations"},
    {"topic": "abbreviations", "question": "'SCM' refers to the:",
     "options": ["Electronic patient record system", "Slit-lamp camera", "Standard cornea map", "Surgical checklist"], "answer": 0,
     "explanation": "SCM is the electronic patient record where results are documented.", "source": "Module 1 — Abbreviations"},
    {"topic": "abbreviations", "question": "'CRAO' stands for:",
     "options": ["Central Retinal Artery Occlusion", "Corneal Refractive Angle Opacity", "Chronic Red Allergic Outbreak", "Central Retinal Anterior Opening"], "answer": 0,
     "explanation": "CRAO = central retinal artery occlusion, a cause of sudden visual loss.", "source": "Module 1 — Abbreviations"},
    {"topic": "abbreviations", "question": "'AMD' stands for:",
     "options": ["Age-Related Macular Degeneration", "Anterior Membrane Disorder", "Acute Macular Detachment", "Average Macular Density"], "answer": 0,
     "explanation": "AMD = age-related macular degeneration.", "source": "Module 1 — Abbreviations"},
]

# ── Ophthalmic investigations pool — OT field ────────────────────────────────
OT_POOL: list[dict] = [
    {"topic": "a-scan biometry", "question": "A-scan biometry mainly measures the eye's:",
     "options": ["Axial length", "Colour vision", "Visual field", "Tear film"], "answer": 0,
     "explanation": "A-scan measures axial length for IOL power calculation.", "source": "Module 1 — A-Scan Biometry"},
    {"topic": "a-scan biometry", "question": "A-scan biometry is mainly indicated for:",
     "options": ["Pre-cataract IOL power calculation", "Glaucoma fields", "Colour vision testing", "Squint measurement"], "answer": 0,
     "explanation": "It is used pre-cataract surgery for IOL power.", "source": "Module 1 — A-Scan Biometry"},
    {"topic": "a-scan biometry", "question": "A-scan biometry uses:",
     "options": ["Ultrasound", "X-ray", "An air puff", "A coloured filter"], "answer": 0,
     "explanation": "A-scan is an ultrasound technique (contact or immersion).", "source": "Module 1 — A-Scan Biometry"},
    {"topic": "optical biometry", "question": "Optical coherence biometry is best described as:",
     "options": ["A non-contact biometry method", "A contact ultrasound", "A blood test", "A dilation drop"], "answer": 0,
     "explanation": "Optical biometry is non-contact and accurate for IOL calculation.", "source": "Module 1 — Optical Coherence Biometry"},
    {"topic": "optical biometry", "question": "An advantage of optical biometry over A-scan is that it is:",
     "options": ["Non-contact and often more accurate", "Cheaper but less accurate", "Faster but contact-based", "Only for children"], "answer": 0,
     "explanation": "Optical biometry is non-contact and more accurate in most eyes.", "source": "Module 1 — Optical Coherence Biometry"},
    {"topic": "biometry", "question": "Biometry for cataract surgery measures axial length, corneal curvature and:",
     "options": ["Anterior chamber depth", "Colour vision", "Eye movements", "Tear break-up time"], "answer": 0,
     "explanation": "Optical biometry captures axial length, K and anterior chamber depth.", "source": "Module 1 — Optical Coherence Biometry"},
    {"topic": "endothelial count", "question": "Endothelial cell count measures the density of cells in the:",
     "options": ["Corneal endothelium", "Retina", "Optic nerve", "Eyelid"], "answer": 0,
     "explanation": "It measures corneal endothelial cell density (cells/mm²).", "source": "Module 1 — Endothelial Cell Count"},
    {"topic": "endothelial count", "question": "A normal endothelial cell count is generally:",
     "options": ["Above 2000 cells/mm²", "Below 500 cells/mm²", "Exactly 100 cells/mm²", "Around 50 cells/mm²"], "answer": 0,
     "explanation": "Normal is >2000 cells/mm²; concern if <1500.", "source": "Module 1 — Endothelial Cell Count"},
    {"topic": "endothelial count", "question": "Endothelial cell count is commonly done before:",
     "options": ["Cataract surgery", "A visual field test", "Colour vision testing", "A fall risk assessment"], "answer": 0,
     "explanation": "Indications include pre-cataract surgery and Fuchs dystrophy.", "source": "Module 1 — Endothelial Cell Count"},
    {"topic": "flare test", "question": "The flare eye test measures aqueous protein as an indicator of:",
     "options": ["Intraocular inflammation", "Eye pressure", "Refractive error", "Tear volume"], "answer": 0,
     "explanation": "Flare reflects protein in the anterior chamber — intraocular inflammation.", "source": "Module 1 — Flare Test"},
    {"topic": "flare test", "question": "The flare test is mainly used to monitor:",
     "options": ["Uveitis", "Cataract", "Squint", "Colour blindness"], "answer": 0,
     "explanation": "It is used for uveitis and post-surgical inflammation.", "source": "Module 1 — Flare Test"},
    {"topic": "hrt", "question": "Heidelberg Retinal Tomography (HRT) scans the:",
     "options": ["Optic nerve head", "Cornea surface", "Eyelid", "Tear ducts"], "answer": 0,
     "explanation": "HRT is 3D laser scanning of the optic nerve head / RNFL.", "source": "Module 1 — HRT"},
    {"topic": "hrt", "question": "HRT is mainly indicated for:",
     "options": ["Glaucoma diagnosis and monitoring", "Cataract grading", "Squint measurement", "Tear film testing"], "answer": 0,
     "explanation": "HRT is used in glaucoma.", "source": "Module 1 — HRT"},
    {"topic": "asoct", "question": "Anterior Segment OCT (ASOCT) images the:",
     "options": ["Cornea, anterior chamber and angle", "Retina only", "Optic nerve only", "Eyelids"], "answer": 0,
     "explanation": "ASOCT gives cross-sectional imaging of the anterior segment.", "source": "Module 1 — ASOCT"},
    {"topic": "asoct", "question": "ASOCT is useful for assessing the drainage angle in:",
     "options": ["Glaucoma", "Conjunctivitis", "Dry eye", "Colour blindness"], "answer": 0,
     "explanation": "Angle assessment (glaucoma) is a key ASOCT indication.", "source": "Module 1 — ASOCT"},
    {"topic": "hvf", "question": "The Humphrey Visual Field (HVF) test maps the patient's:",
     "options": ["Visual field", "Eye pressure", "Corneal thickness", "Colour vision"], "answer": 0,
     "explanation": "HVF is automated perimetry that maps field sensitivity.", "source": "Module 1 — HVF"},
    {"topic": "hvf", "question": "The most common HVF programmes for glaucoma are:",
     "options": ["24-2 or 30-2", "10-1 or 5-5", "60-4 only", "1-1"], "answer": 0,
     "explanation": "24-2 or 30-2 (SITA Standard/Fast) are standard for glaucoma.", "source": "Module 1 — HVF"},
    {"topic": "hvf", "question": "Which tells you whether an HVF test was reliable?",
     "options": ["Fixation losses and false positive/negative rates", "The patient's age", "Room temperature", "The chart colour"], "answer": 0,
     "explanation": "Reliability indices are fixation losses and false pos/neg.", "source": "Module 1 — HVF"},
    {"topic": "hvf", "question": "An arcuate (Bjerrum) scotoma on a field points to:",
     "options": ["Glaucoma", "A cataract", "Dry eye", "Conjunctivitis"], "answer": 0,
     "explanation": "Arcuate/Bjerrum scotoma is a glaucomatous pattern.", "source": "Module 1 — HVF"},
    {"topic": "hvf", "question": "A hemianopia (half-field loss) suggests a problem that is:",
     "options": ["Neurological", "In the eyelid", "In the tear duct", "On the cornea"], "answer": 0,
     "explanation": "Hemianopia points to a chiasm/optic tract (neurological) lesion.", "source": "Module 1 — HVF"},
    {"topic": "gvf", "question": "Goldman Visual Field (GVF) testing is:",
     "options": ["Manual kinetic perimetry", "An automated air-puff test", "An ultrasound scan", "A colour test"], "answer": 0,
     "explanation": "GVF is manual kinetic perimetry mapping isopters.", "source": "Module 1 — GVF"},
    {"topic": "gvf", "question": "A key advantage of GVF is that it can:",
     "options": ["Test very large fields and uncooperative patients", "Replace cataract surgery", "Measure IOP", "Map the cornea"], "answer": 0,
     "explanation": "GVF suits large fields and patients who cannot do automated tests.", "source": "Module 1 — GVF"},
    {"topic": "pam", "question": "The Potential Acuity Meter (PAM) predicts:",
     "options": ["Likely vision after cataract surgery", "Eye pressure", "Colour vision", "Tear volume"], "answer": 0,
     "explanation": "PAM projects a chart onto the retina to predict post-op VA.", "source": "Module 1 — PAM"},
    {"topic": "pam", "question": "PAM testing usually requires:",
     "options": ["Pupil dilation", "An air puff", "A blood sample", "A contact lens"], "answer": 0,
     "explanation": "Dilation is needed for PAM.", "source": "Module 1 — PAM"},
    {"topic": "corneal topography", "question": "Corneal topography maps the cornea's:",
     "options": ["Curvature and elevation", "Colour", "Pressure", "Tear volume"], "answer": 0,
     "explanation": "Topography maps corneal curvature and elevation.", "source": "Module 1 — Corneal Topography"},
    {"topic": "corneal topography", "question": "Corneal topography is commonly used to screen for:",
     "options": ["Keratoconus and pre-LASIK suitability", "Glaucoma fields", "Colour blindness", "Cataract density"], "answer": 0,
     "explanation": "Indications include keratoconus screening and pre-LASIK.", "source": "Module 1 — Corneal Topography"},
    {"topic": "corneal topography", "question": "A keratoconus pattern on topography shows:",
     "options": ["Inferior corneal steepening / asymmetric bow-tie", "A flat, regular cornea", "A normal symmetric map", "A clear lens"], "answer": 0,
     "explanation": "Keratoconus shows inferior steepening and irregular astigmatism.", "source": "Module 1 — Corneal Topography"},
    {"topic": "pentacam", "question": "A Pentacam scan maps the:",
     "options": ["Cornea (shape and thickness)", "Retina", "Optic nerve", "Tear ducts"], "answer": 0,
     "explanation": "Pentacam is Scheimpflug imaging of corneal shape and thickness.", "source": "OSCE — Pentacam"},
    {"topic": "oct", "question": "'OCT' stands for:",
     "options": ["Optical Coherence Tomography", "Ocular Contact Test", "Optic Curve Tracing", "Outer Cornea Test"], "answer": 0,
     "explanation": "OCT = Optical Coherence Tomography.", "source": "Module 1 — Investigations"},
    {"topic": "oct", "question": "An OCT scan is:",
     "options": ["A non-contact scan of the retinal layers", "A contact ultrasound", "An eye-pressure test", "A blood test"], "answer": 0,
     "explanation": "OCT is a non-contact optical scan of the retina/optic nerve.", "source": "OSCE — Cirrus OCT"},
    {"topic": "macular oct", "question": "Increased central macular thickness with fluid on OCT suggests:",
     "options": ["Macular oedema / fluid", "A healthy macula", "A cataract", "Dry eye"], "answer": 0,
     "explanation": "Increased thickness with fluid indicates macular oedema.", "source": "OSCE — Cirrus OCT"},
    {"topic": "rnfl", "question": "Thinning of the retinal nerve fibre layer (RNFL) on OCT is associated with:",
     "options": ["Glaucoma", "Dry eye", "Conjunctivitis", "Refractive error"], "answer": 0,
     "explanation": "RNFL thinning reflects the optic nerve damage of glaucoma.", "source": "OSCE — Cirrus OCT"},
    {"topic": "intraocular pressure", "question": "The normal range of intraocular pressure is:",
     "options": ["10–21 mmHg", "21–35 mmHg", "0–7 mmHg", "35–50 mmHg"], "answer": 0,
     "explanation": "Normal IOP is about 10–21 mmHg.", "source": "Module 1 — IOP / NCT"},
    {"topic": "basic evaluation", "question": "By convention, which eye is tested first?",
     "options": ["The right eye", "The left eye", "Both together", "Either, randomly"], "answer": 0,
     "explanation": "Start with the right eye by convention.", "source": "Module 1 — Basic Eye Evaluation"},
    {"topic": "auto-refraction", "question": "Auto-refraction objectively measures:",
     "options": ["Refractive error", "Eye pressure", "Colour vision", "Tear volume"], "answer": 0,
     "explanation": "AR measures refractive error (myopia, hyperopia, astigmatism).", "source": "Module 1 — Auto-Refraction"},
    {"topic": "keratometry", "question": "Auto-keratometry is especially important before:",
     "options": ["Cataract surgery (IOL calculation)", "A colour vision test", "A fall risk assessment", "Lid hygiene"], "answer": 0,
     "explanation": "AK measures corneal curvature for IOL power calculation.", "source": "Module 1 — Auto-Keratometry"},
    {"topic": "biometry accuracy", "question": "An unstable tear film (dry eye) most affects which measurement?",
     "options": ["Keratometry (K) readings", "Axial length only", "The patient's name", "Pupil colour"], "answer": 0,
     "explanation": "Keratometry reads the front surface, so dry eye distorts K values.", "source": "OSCE — Optical biometer"},
    {"topic": "dayward", "question": "The pre-op mnemonic 'DISM' stands for:",
     "options": ["Diagnosis, Indication, Surgery, Medical condition", "Drop, Inject, Scan, Measure", "Distance, IOP, Sight, Macula", "Dilate, Irrigate, Suture, Monitor"], "answer": 0,
     "explanation": "DISM = Diagnosis, Indication, Surgery planned, Medical conditions.", "source": "Module 1 — Dayward Pre-Op"},
    {"topic": "anaesthesia", "question": "Anaesthesia for eye surgery may be GA, topical or:",
     "options": ["Local anaesthesia (LA)", "Herbal", "Inhaled only", "None ever"], "answer": 0,
     "explanation": "Types are GA, LA and topical.", "source": "Module 1 — Dayward / OT"},
    {"topic": "dayward", "question": "Post-operative monitoring in dayward includes recording:",
     "options": ["BP, RR and PR", "Colour vision", "Tear volume", "Glasses power"], "answer": 0,
     "explanation": "Monitor blood pressure, respiratory rate and pulse rate.", "source": "Module 1 — Dayward Post-Op"},
    {"topic": "abbreviations", "question": "'HVF' stands for:",
     "options": ["Humphrey Visual Field", "High Vision Filter", "Half Visual Focus", "Hyperopia Vision Factor"], "answer": 0,
     "explanation": "HVF = Humphrey Visual Field.", "source": "Module 1 — Abbreviations"},
    {"topic": "abbreviations", "question": "'GVF' stands for:",
     "options": ["Goldman Visual Field", "Glaucoma Vision Filter", "General Visual Function", "Grey Visual Field"], "answer": 0,
     "explanation": "GVF = Goldman Visual Field.", "source": "Module 1 — Abbreviations"},
    {"topic": "abbreviations", "question": "'HRT' stands for:",
     "options": ["Heidelberg Retinal Tomography", "High Resolution Tonometry", "Hyperopic Refraction Test", "Hand-held Retinal Torch"], "answer": 0,
     "explanation": "HRT = Heidelberg Retinal Tomography.", "source": "Module 1 — Abbreviations"},
    {"topic": "abbreviations", "question": "'ASOCT' stands for:",
     "options": ["Anterior Segment Optical Coherence Tomography", "Auto-Scan Ocular Contact Test", "Angle Sweep Ocular CT", "Anterior Sclera Optic CT"], "answer": 0,
     "explanation": "ASOCT = anterior segment OCT.", "source": "Module 1 — Abbreviations"},
    {"topic": "abbreviations", "question": "'PAM' stands for:",
     "options": ["Potential Acuity Meter", "Pupil Angle Monitor", "Posterior Anterior Map", "Peripheral Acuity Measure"], "answer": 0,
     "explanation": "PAM = Potential Acuity Meter.", "source": "Module 1 — Abbreviations"},
    {"topic": "abbreviations", "question": "'RNFL' stands for:",
     "options": ["Retinal Nerve Fibre Layer", "Refractive Near Focus Lens", "Retinal Normal Fluid Level", "Rapid Non-contact Field Light"], "answer": 0,
     "explanation": "RNFL = retinal nerve fibre layer.", "source": "Module 1 — Abbreviations"},
    {"topic": "imaging quality", "question": "If a scan shows motion artefact or the patient blinked, you should:",
     "options": ["Repeat the scan", "Accept it anyway", "Delete the record", "Lower the lights only"], "answer": 0,
     "explanation": "Poor-quality captures should be repeated.", "source": "OSCE — imaging scripts"},
    {"topic": "patient safety", "question": "Before any scan you must confirm the patient's identity and the:",
     "options": ["Correct eye / test ordered", "Weather", "Lunch time", "Wi-Fi password"], "answer": 0,
     "explanation": "Confirm identity and the correct eye/test before scanning.", "source": "OSCE — imaging scripts"},
    {"topic": "scope of practice", "question": "If a scan shows an abnormality, the technician should:",
     "options": ["Report the findings to the doctor", "Diagnose and prescribe", "Tell the patient the diagnosis", "Ignore it"], "answer": 0,
     "explanation": "Technicians report findings; the doctor diagnoses.", "source": "Module 1 — Investigations"},
    {"topic": "optical biometry", "question": "Besides cataract surgery, optical biometry can also be used for:",
     "options": ["Contact lens fitting", "Colour vision testing", "Fall risk scoring", "Lid hygiene"], "answer": 0,
     "explanation": "Optical biometry is also indicated for contact lens fitting.", "source": "Module 1 — Optical Coherence Biometry"},
]

# OA and PSA share the clinical base (they study almost the same course);
# OT gets the ophthalmic investigations pool.
CHECKIN_QUESTION_POOL: dict[str, list[dict]] = {
    "OA": CLINICAL_POOL,
    "PSA": CLINICAL_POOL,
    "OT": OT_POOL,
}
